<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'lexik_jwt_authentication.encoder.default' shared service.

return $this->services['lexik_jwt_authentication.encoder.default'] = new \Lexik\Bundle\JWTAuthenticationBundle\Encoder\DefaultEncoder(${($_ = isset($this->services['lexik_jwt_authentication.jws_provider.default']) ? $this->services['lexik_jwt_authentication.jws_provider.default'] : $this->load('getLexikJwtAuthentication_JwsProvider_DefaultService.php')) && false ?: '_'});
