<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'maindbundle.contains_mail_validator' shared service.

return $this->services['maindbundle.contains_mail_validator'] = new \MainBundle\Validator\Constraints\ContainsMailValidator($this->parameters['mails_suffixe']);
