framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    trusted_hosts: ~
    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: session.handler.native_file
        cookie_secure: auto
        cookie_samesite: lax

    fragments: ~
    http_method_override: true
    assets: ~
    #esi: true
    #fragments: true
    php_errors:
        log: true

