fos_rest:
    body_converter:
        enabled: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
    view:
        view_response_listener: true
    param_fetcher_listener: true
    routing_loader:
        default_format: json